// 개발용 목 데이터
import type { ArticlesResponse } from "@/entities/article";

// 인기 태그 목록
export const mockTags: string[] = [
  "dragons",
  "training",
  "react",
  "javascript",
  "hooks",
  "typescript",
  "programming",
  "nextjs",
  "web",
];

export const mockArticles: ArticlesResponse = {
  articles: [
    {
      slug: "how-to-train-your-dragon",
      title: "How to train your dragon",
      description: "Ever wonder how?",
      body: "It takes a Jacobian",
      tagList: ["dragons", "training"],
      createdAt: "2024-01-15T10:00:00.000Z",
      updatedAt: "2024-01-15T10:00:00.000Z",
      favorited: false,
      favoritesCount: 152,
      author: {
        username: "jake",
        bio: "I work at statefarm",
        image: "https://api.realworld.io/images/smiley-cyrus.jpeg",
        following: false,
      },
    },
    {
      slug: "how-to-train-your-dragon-2",
      title: "How to train your dragon 2",
      description: "So toothless",
      body: "It a]lotta patience",
      tagList: ["dragons", "training"],
      createdAt: "2024-01-14T10:00:00.000Z",
      updatedAt: "2024-01-14T10:00:00.000Z",
      favorited: false,
      favoritesCount: 89,
      author: {
        username: "jake",
        bio: "I work at statefarm",
        image: "https://api.realworld.io/images/smiley-cyrus.jpeg",
        following: false,
      },
    },
    {
      slug: "understanding-react-hooks",
      title: "Understanding React Hooks",
      description: "A deep dive into React Hooks",
      body: "React Hooks are amazing...",
      tagList: ["react", "javascript", "hooks"],
      createdAt: "2024-01-13T10:00:00.000Z",
      updatedAt: "2024-01-13T10:00:00.000Z",
      favorited: true,
      favoritesCount: 234,
      author: {
        username: "johndoe",
        bio: "Frontend developer",
        image: "https://api.realworld.io/images/demo-avatar.png",
        following: true,
      },
    },
    {
      slug: "typescript-best-practices",
      title: "TypeScript Best Practices",
      description: "Learn how to write better TypeScript",
      body: "TypeScript helps catch errors early...",
      tagList: ["typescript", "javascript", "programming"],
      createdAt: "2024-01-12T10:00:00.000Z",
      updatedAt: "2024-01-12T10:00:00.000Z",
      favorited: false,
      favoritesCount: 178,
      author: {
        username: "janedoe",
        bio: "Full-stack developer",
        image: "https://api.realworld.io/images/demo-avatar.png",
        following: false,
      },
    },
    {
      slug: "nextjs-app-router",
      title: "Next.js App Router Guide",
      description: "Everything you need to know about App Router",
      body: "The App Router is a new paradigm...",
      tagList: ["nextjs", "react", "web"],
      createdAt: "2024-01-11T10:00:00.000Z",
      updatedAt: "2024-01-11T10:00:00.000Z",
      favorited: false,
      favoritesCount: 312,
      author: {
        username: "vercel_dev",
        bio: "Building the future of the web",
        image: "https://api.realworld.io/images/demo-avatar.png",
        following: true,
      },
    },
  ],
  articlesCount: 5,
};
